version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: jakarta.servlet:jakarta.servlet-api
    versions:
    - ">= 5.a, < 6"
  - dependency-name: io.grpc:grpc-netty
    versions:
    - 1.35.0
    - 1.36.1
  - dependency-name: org.jboss.resteasy:resteasy-servlet-initializer
    versions:
    - 3.14.0.Final
    - 3.15.0.Final
    - 3.15.1.Final
  - dependency-name: org.jboss.resteasy:resteasy-jaxb-provider
    versions:
    - 3.14.0.Final
    - 3.15.0.Final
    - 3.15.1.Final
  - dependency-name: org.jboss.resteasy:resteasy-jaxrs
    versions:
    - 3.14.0.Final
    - 3.15.0.Final
    - 3.15.1.Final
  - dependency-name: org.jboss.resteasy:resteasy-client
    versions:
    - 3.14.0.Final
    - 3.15.0.Final
    - 3.15.1.Final
  - dependency-name: org.jboss.resteasy:resteasy-json-binding-provider
    versions:
    - 3.14.0.Final
    - 3.15.0.Final
    - 3.15.1.Final
  - dependency-name: org.jboss.resteasy:resteasy-cdi
    versions:
    - 3.14.0.Final
    - 3.15.0.Final
    - 3.15.1.Final
  - dependency-name: io.smallrye:smallrye-parent
    versions:
    - "25"
  - dependency-name: org.eclipse.jetty:jetty-maven-plugin
    versions:
    - 11.0.0
  - dependency-name: io.opentelemetry:opentelemetry-exporters-otlp
    versions:
    - 0.9.1
  - dependency-name: io.opentelemetry:opentelemetry-exporters-logging
    versions:
    - 0.9.1
  - dependency-name: io.opentelemetry:opentelemetry-proto
    versions:
    - 0.9.1
  - dependency-name: io.opentelemetry:opentelemetry-sdk
    versions:
    - 0.9.1
  - dependency-name: io.opentelemetry:opentelemetry-api
    versions:
    - 0.9.1
