name: SmallRye Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'NOTICE'
      - 'README*'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'NOTICE'
      - 'README*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11, 17]
    name: build with jdk ${{matrix.java}}

    steps:
      - uses: actions/checkout@v2
        name: checkout

      - uses: actions/setup-java@v1
        name: set up jdk ${{matrix.java}}
        with:
          java-version: ${{matrix.java}}

      - name: build with maven
        run: mvn -B formatter:validate verify --file pom.xml

  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        java: [11]
    name: build with jdk ${{matrix.java}} windows

    steps:
      - uses: actions/checkout@v2
        name: checkout

      - uses: actions/setup-java@v1
        name: set up jdk ${{matrix.java}}
        with:
          java-version: ${{matrix.java}}

      - name: build with maven
        run: mvn -B formatter:validate verify --file pom.xml

