name: SmallRye Release

on:
  pull_request:
    types: [ closed ]
    paths:
      - '.github/project.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare-release:
    name: Prepare Release
    if: ${{ github.event.pull_request.merged == true}}
    uses: smallrye/.github/.github/workflows/prepare-release.yml@main
    secrets: inherit

  publish-tck:
    name: Publish TCK Report
    needs: prepare-release
    uses: ./.github/workflows/publish-tck.yml
    secrets: inherit
    with:
      version: ${{needs.prepare-release.outputs.release-version}}

#  perform-release:
#    name: Perform Release
#    needs: prepare-release
#    uses: smallrye/.github/.github/workflows/perform-release.yml@main
#    secrets: inherit
#    with:
#      version: ${{needs.prepare-release.outputs.release-version}}
